### ISSUE TITLE
Optimizacije

### ISSUE THREAD

**Issue by k3ap** [k3ap/prog2-go#16]
- [x] Ne poglej vseh polj za potezo, ampak samo najbolj zanimiva polja
- [ ] Dinamična določitev največje globine v alphabeta algoritmu

**Comment by k3ap** [comment]
Za zanimive poteze lahko dava npr. vsa polja, ki so oddaljena največ dva koraka od že položenega kamna.
Če je kamnov na plošči zelo malo, pa lahko dodaš npr. še vsa polja, oddaljena vsaj 2 koraka od roba.
Nisem testiral, kako dobro to dejansko bo, ampak opažam, da algoritmi pogosto vzamejo take poteze.

**Comment by jakavel** [comment]
Iz profesorjevega videa:

- [ ] Če ocenjevalna funkcija kadarkoli pride do "prisiljene" poteze (glej sliko) jo avtomatsko naredi in nadaljuje raziskovanje, brez da bi zmanjšala globino zaradi narejene poteze.
![forced_move](https://github.com/k3ap/prog2-go/assets/50873076/d74d6f1b-1756-4f13-9aff-dc5e6b6ffbc0)
- [ ] Dinamično poveča globino iskanja, mogoče glede na število postavljenih kamnov?

**Comment by k3ap** [comment]
- [ ] v alphabeti si lahko hraniš možne poteze v eni množici, da ni treba vedno na novo računati

**Comment by k3ap** [comment]
>     * [ ]  Če ocenjevalna funkcija kadarkoli pride do "prisiljene" poteze (glej sliko) jo avtomatsko naredi in nadaljuje raziskovanje, brez da bi zmanjšala globino zaradi narejene poteze.

To lahko narediva tako, da pogledava, če ima kakšna komponenta natanko eno svobodo.

**Comment by k3ap** [comment]
- [ ] združi iskanje vsega za estimator v eno funkcijo, ki vrne dve vrednosti
