### ISSUE TITLE
Igra go

### ISSUE THREAD

**Issue by k3ap** [k3ap/prog2-go#17]
Spremembe od first capture pravil:
- 19x19 grid (verjetno lahko izbiro velikosti mreže dopuščava uporabniku)
- Lahko predaš potezo nasprotniku
- Če ujameš skupino kamnov, se odstranijo iz plošče. Prvo se ujame nasprotnikove kamne, potem tvoje.
- Nobeno stanje plošče se nikdar ne sme ponoviti.
- Igra se konča, ko pride do dveh zaporednih predaj poteze
- Zmaga tisti igralec, ki ima na koncu igre več teritorija; t.j. število njegovih kamnov in število praznih polj, katerih povezano kompnento obdajajo samo kamni njegove barve

**Comment by jakavel** [comment]
Stvari, ki jih je treba še naredit, da ne pozabim:
- [ ] Pravilo ko (ponavljane plošče)
- [ ] Mogoče bi lahko sproti povedal točke

**Comment by k3ap** [comment]
Možna optimizacija za `captureComponentsOf`; novo iskanje po grafu, ki samo doda na novo prazna polja kot svobode na rob nove prazne komponente

**Comment by k3ap** [comment]
Je tole še treba pustiti odprto?

**Comment by jakavel** [comment]
Dobro bi bilo še dodati možnost, da spremeniš velikost polja.
