### ISSUE TITLE
Prevodi

### ISSUE THREAD

**Issue by k3ap** [k3ap/prog2-go#20]
Inteligenca.java (in morda še kaj) nima vsega prevedenega (razni komentarji, lokalne spremenljivke, ...)

**Comment by k3ap** [comment]
@jakavel je morda smiselno, da prevedeva vse, zdaj ko ni več tekmovanja?

**Comment by jakavel** [comment]
Misliš tudi obvezna imena razredov in metod iz tekmovanja?

**Comment by k3ap** [comment]
Ja

**Comment by k3ap** [comment]
Mislim da ne bo prišlo do tega.
